SEEWeb/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Model;
using PagedList;
using SEEWeb.ViewModel;
using System.Net;
using System.Data.Entity;

namespace SEEWeb.Controllers
{
    public class AlbumController : Controller
    {
        AlbumManager albumm = new AlbumManager();
        Album_CommentManager albcm = new Album_CommentManager();
        SEEEntities db = new SEEEntities();
        #region 相册主页
        // GET: Album
        public ActionResult Index()
        {
            var album1 = (from p in db.Album select p).ToList().OrderByDescending(p => p.Album_Point.Count()).ToList();//显示点赞最多的八个相册
            
            return View(album1);   
        }
        #endregion

        #region 相册创建
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Album album)
        {
            HttpPostedFileBase file = Request.Files["albumimage"];
            if (Session["UID"] != null)
            {
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        string filePath = file.FileName;
                        string fileName = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                        string serverpath = Server.MapPath(@"\images\albums\") + fileName;
                        string relativepath = @"/images/albums/" + fileName;
                        file.SaveAs(serverpath);
                        album.Alb_Pic = relativepath;
                    }
                    album.UID = Convert.ToInt32(Session["UID"].ToString());
                    album.Alb_Time = DateTime.Now;
                    albumm.Add(album);
                    return Content("<script>alert('添加成功！');window.open('" + Url.Action("Index", "Album") + "','_self');</script>");
                }
            }
            else
            {
                return Content("<script>;alert('你还没有登陆哦!');history.go(-1)</script>");
            }            
            return View(album);
        }
        #endregion

        #region 相册主页实现分页
        public ActionResult Album(int ? page)
        {
            var album = (from p in db.Album select p).ToList().OrderByDescending(a=>a.Alb_Time).ToList();//根据点赞数排列;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(album.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Album1(int ? page)
        {
            int UID = Convert.ToInt32(Session["UID"].ToString());
            var album = from a in db.Album.OrderByDescending(a => a.Alb_Time).Where(p => p.UID == UID).ToList()
                        select a;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(album.ToPagedList(pageNumber, pageSize));
        }
        #endregion

        #region 相册详细
        public ActionResult Details(int id)
        {
            Album albums = db.Album.Find(id);
            int point = albums.Album_Point.Count();
            ViewBag.pc = point;
            Album_Point ap = db.Album_Point.Find(id);
            var picture_in_album = from p in db.Picture_In_Album.Where(p => p.Alb_ID == id)
                          select p;
            //var pictures = (from p in db.Picture_In_Album select p).Where(p => p.Alb_ID == id).ToList();
            var albpoint = from p in db.Album_Point.Where(p => p.Alb_ID == id)
                           select p;
            var album1 = from a in db.Album.OrderByDescending(p => p.Alb_Time)
                         select a;
            var album_comment = from m in db.Album_Comment.Where(p => p.Alb_ID == id).OrderByDescending(p => p.AC_Time)
                                select m;
            var album_save = from m in db.Album_Save.Where(p => p.Alb_ID == id)
                             select m;
            var index = new SEEWeb.ViewModel.AlbumViewModel()
            {
                Album1 = albums,
                Album2 = album1,
                Album_Comment = album_comment,
                Album_Point = albpoint,
                Album_Save = album_save,
                Picture_In_Album=picture_in_album,
            };
            return View(index);
        }
        #endregion

        #region 相册评论
        [HttpPost]
        public ActionResult AC_Add(Album_Comment album_comment)
        {
            if(Session["UID"] != null)
            {
                string acmes = Request["acmes"];
                int alb_id = Convert.ToInt32(Request["albid"]);
                if (ModelState.IsValid)
                {
                    album_comment.Alb_ID = alb_id;
                    album_comment.UID = Convert.ToInt32(Session["UID"].ToString());
                    album_comment.AC_Mes = acmes;
                    album_comment.AC_Time = System.DateTime.Now;
                    db.Album_Comment.Add(album_comment);
                    db.SaveChanges();
                    return Content("<script>alert('评论成功！');window.open('" + Url.Action("Details", "Album", new { id = alb_id }) + "','_self');</script>");
                }
                return RedirectToAction("Details", "Album");
            }
            else
            {
                return Content("<script>;alert('你还没有登陆哦!');history.go(-1)</script>");
            }

        }
        #endregion

        #region 相册点赞
        public JsonResult Point(Album_Point albpoint,int Alb_ID)
        {
            var list = new List<PointList>();
            var album = db.Album.Find(Alb_ID);
            int albid = Alb_ID;
            int UID = Convert.ToInt32(Session["UID"].ToString());
            int chk_member = db.Album_Point.Where(p => p.UID == UID).Where(p => p.Alb_ID == albid).Count();
            if(chk_member != 1)
            {
                if(ModelState.IsValid)
                {
                    albpoint.Alb_ID = albid;
                    albpoint.UID = UID;
                    albpoint.AP_Time = DateTime.Now;
                    db.Album_Point.Add(albpoint);
                    db.SaveChanges();
                }
            }
            var sum = db.Album_Point.Where(a => a.Alb_ID == albid).ToList().Count();
            for(int i = 1;i <= 1; i++)
            {
                PointList pl = new PointList();
                pl.sum = sum;
                pl.succ = chk_member;
                list.Add(pl);
            }
            return Json(list);
        }
        #endregion

        #region 相册收藏
        public JsonResult Save(Album_Save albsave,int Alb_ID)
        {
            var list = new List<PointList>();
            var album = db.Album.Find(Alb_ID);
            int albid = Alb_ID;
            int UID = Convert.ToInt32(Session["UID"].ToString());
            int chk_member = db.Album_Save.Where(p => p.UID == UID).Where(p => p.Alb_ID == albid).Count();
            if(chk_member != 1)
            {
                if (ModelState.IsValid)
                {
                    albsave.Alb_ID = albid;
                    albsave.UID = UID;
                    albsave.AS_Time = DateTime.Now;
                    db.Album_Save.Add(albsave);
                    db.SaveChanges();
                }
            }
            var sum = db.Album_Save.Where(a => a.Alb_ID == albid).ToList().Count();
            for(int i = 1;i <= 1; i++)
            {
                PointList pl = new PointList();
                pl.sum = sum;
                pl.succ = chk_member;
                list.Add(pl);
            }
            return Json(list);
        }
        #endregion

        #region 删除相册
        public ActionResult Delete(int id)
        {
            var temp = albumm.Remove(id);
            if (temp == true)
                return Content("<script>alert('删除成功！');window.open('" + Url.Action("List", "Album") + "','_self');</script>");
            else
                return View();
        }

        public ActionResult Delete1(int id)
        {
            var temp = albumm.Remove(id);
            if (temp == true)
                return Content("<script>;alert('删除成功!');history.go(-1)</script>");
            else
                return View();
        }
        #endregion

        #region 后台管理
        public ActionResult List(int ? page,string search)
        {
            var list = new List<Album>();
            if(search != null)
            {
                var alb = (from p in db.Album select p).Where(a => (a.Alb_Name.Contains(search)) || (a.Alb_Mes.Contains(search)) || (a.UserInfo.User_Name.Contains(search))).ToList();
                list = alb;
            }
            else
            {
                var alb = albumm.List();
                list = alb;
            }
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        #endregion
    }
}

SEEWeb/Controllers/Picture_In_AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SEEWeb.ViewModel;
using PagedList;
using BLL;
using Model;
using System.Data.Entity;

namespace SEEWeb.Controllers
{
    public class Picture_In_AlbumController : Controller
    {
        SEEEntities db = new SEEEntities();
        // GET: Picture_In_Album
        public ActionResult Index(int id)
        {
            Album album = db.Album.Find(id);
            var pictures = (from p in db.Picture_In_Album select p).Where(p => p.Alb_ID == id).ToList();
            return View(pictures);
        }

        #region 添加图片进相册
        public ActionResult Add(int Pic_ID)
        {
            if(Session["UID"] != null)
            {
                int userid = Convert.ToInt32(Session["UID"].ToString());
                var album = from p in db.Album.Where(p => p.UID == userid)
                            select p;
                var picture = db.Picture.Find(Pic_ID);
                var pictureinalbum = new ViewModel.AlbumViewModel
                {
                    Album2 = album,
                    Picture = picture,
                };
                return View(pictureinalbum);
            }
            else
            {
                return Content("<script>;alert('你还没有登陆哦!');history.go(-1)</script>");
            }          

        }
        
        public ActionResult Add2(Picture_In_Album pia,int albid,int picid)
        {
           if(Session["UID"]!=null)
            {
                if (ModelState.IsValid)
                {
                pia.Alb_ID = albid;
                pia.Pic_ID = picid;
                pia.PIA_Time = DateTime.Now;
                db.Picture_In_Album.Add(pia);
                db.SaveChanges();
                return Content("<script>;alert('添加成功');history.go(-2)</script>");
                }
                  return RedirectToAction("Details", "Picture");
            }
            else
            {
                return Content("<script>;alert('你还没有登陆哦!');history.go(-1)</script>");
            }
        }
        #endregion
    }
}

SEEWeb/Views/Album/Add.cshtml
@model Model.Album

@{
    ViewBag.Title = "Add";
}
<link href="~/Content/layui/css/layui.css" rel="stylesheet" />
<section class="section-background">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Index")">主页</a></li>
            <li class="active"><a href="@Url.Action("Index","Album")">&nbsp;相册</a></li>
            <li class="active"><a href="#">相册创建</a></li>
        </ol>


    </div>
</section>
<section class="about" id="about" style="background: #f3f3f3;">
    <div class="container section-wrapper">
        <h2 class="section-title black">
            创  建  相  册
        </h2>
        <div class="underline purple"></div>

        @using (Html.BeginForm("Add", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-horizontal">
            <div class="col-sm-3 col-xs-12 form-group">
                &nbsp;
            </div>
            <div class="col-sm-2 col-xs-12 form-group">
                &nbsp;
            </div>
            <div class="col-sm-4 col-xs-12 form-group">
                <div class="layui-form">
                    <div class="layui-form-item">
                        <div>
                            @Html.EditorFor(model => model.Alb_Name, new { htmlAttributes = new { @class = "layui-input", placeholder = "请输入相册名称" } })
                            @Html.ValidationMessageFor(model => model.Alb_Name)
                        </div>
                        <br /><br />
                        <div>
                            @Html.EditorFor(model => model.Alb_Mes, new { htmlAttributes = new { @class = "layui-input", placeholder = "请输入相册简介" } })
                            @Html.ValidationMessageFor(model => model.Alb_Mes)
                        </div>
                        <br /><br />
                        <div>
                            <input type="file" name="albumimage" />
                        </div>
                        <div style="float:right;margin-top:30px;">
                            <input type="submit" value="创建相册" class="btn" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }


    </div>
</section>

  

SEEWeb/Views/Album/Album.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Model.Album>
@{
    ViewBag.Title = "Album";
    Layout = null;
}

<!DOCTYPE html>
<style>
</style>
<section class="portfolio" id="portfolio">
    <div class="container section-wrapper">
        <h2 class="section-title black">
            相  册
        </h2>
        <div class="underline purple"></div>
        <div class="row">
            @foreach (var p in Model)
            {
                <div class="col-sm-4 col-xs-6">
                    <div class="portfolio-item">
                        <div class="portfolio-img">
                                <img src="@p.Alb_Pic" alt="port3" height="280" />
                         
                            <div class="portfolio-img-hover">
                                <a href="@Url.Action("Details",new {id=p.Alb_ID})"><img src="~/Content/_share/User/assets/images/plus.png" class="plus"></a>
                            </div>
                        </div>
                        <div class="portfolio-item-details">
                            <div class="portfolio-item-name">
                                <a href="@Url.Action("Details",new {id=p.Alb_ID})"> @p.Alb_Name  </a>   <br />   
                                <small> 
                                    <a href="@Url.Action("UserIndex","User",new {UID=p.UserInfo.UID})">@p.UserInfo.User_Name  </a>
                                </small>
                            </div>
                            <div class="port-heart">
                                <i class="ion-ios-heart-outline"></i>  @p.Album_Point.Count()
                            </div>
                        </div>

                    </div>
                </div>
            }




        </div>
    </div>
    <div  class="container"  >
        <div style="float:right">
            <div>
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </div>
            <div>
                @Html.PagedListPager(Model, page => Url.Action("Index", "Album", new { page }))
            </div>
        </div>
     
    </div>
</section>
     

SEEWeb/Views/Album/Album1.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Model.Album>
@{
    ViewBag.Title = "Album";
 
}

<!DOCTYPE html>

<link href="~/Content/_share/User/assets/css/service.css" rel="stylesheet" />
<section class="section-background">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Index")">主页</a></li>

            <li class="active"><a href="@Url.Action("UserCenter","User")">&nbsp;用户中心</a></li>
            <li class="active">&nbsp; 我的相册</li>
        </ol>
    </div>
</section>
<section class="portfolio" id="portfolio">
    <div class="container section-wrapper">
        <h2 class="section-title black">
            我 的 相 册
        </h2>
        <div class="underline purple"></div>
        <div class="row">
            <div class="col-sm-1 col-xs-6">
                &nbsp;
            </div>
            <div class="col-sm-4 col-xs-6">

                <div class="portfolio-item">
                    <a href="@Url.Action("UserCenter","User")"><h2>  <span class="label label-primary">我的信息</span></h2></a>
                    <br />
                    <a href="@Url.Action("Album1","Album")"><h2>  <span class="label label-primary">我的相册</span></h2></a>
                    <br />
                    <a href="@Url.Action("Picture1","Picture")"><h2><span class="label label-primary">我的图片</span> </h2></a>
                    <br />
                    <a href="@Url.Action("Save","User")"><h2> <span class="label label-primary">我的收藏</span></h2></a>
                    <br />
                    <a href="@Url.Action("focusme","User")"><h2><span class="label label-primary">我的粉丝</span> </h2></a>
                    <br />
                    <a href="@Url.Action("focus","User")"><h2><span class="label label-primary">我关注的</span> </h2></a>
                </div>
            </div>
            <div class="col-sm-7 col-xs-6">

                @foreach (var p in Model)
                {
                    <div class="col-sm-4 col-xs-6">
                        <div>
                            <a href="@Url.Action("Details",new {id=p.Alb_ID})">
                                <img height="130" width="200" src="@p.Alb_Pic" />
                            </a>
                        </div>
                   
                        <div>
                            @p.Alb_Name
                        </div>
                        <br />
                        <div>
                            @p.Alb_Time
                        </div>
                        <div>

                            <a href="@Url.Action("Delete1","Album",new { id = p.Alb_ID})"><span class="label label-warning" style="float:right"> 删除</span></a>
                        </div>
                        </div>
                 }



                    </div>
                    <div style="float:right;">
                        <div>
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        </div>
                        <div>
                            @Html.PagedListPager(Model, page => Url.Action("Album1", "Album", new { page }))
                        </div>
                    </div>

                </div>
    </div>
</section>

SEEWeb/Views/Album/Details.cshtml
@using PagedList.Mvc
@using Model
@model SEEWeb.ViewModel.AlbumViewModel
@{
    ViewBag.Title = "Details";
}
<!DOCTYPE html>
<head>
    <script type="text/javascript">
        function asyncPoint(alp) {
            $.ajax({
                url: "/Album/Point",
                async: false,
                type: "post",
                data: { Alb_ID: alp },
                dataType: "json",
                success: function (list) {
                    var data = eval(list);
                    $("#sum").val(data[0].sum);
                    $("#sum").text(data[0].sum);
                    if (data[0].succ == 1) {
                        alert("你已经点过赞了哦");
                    } else {
                        alert("点赞成功");
                    }
                }
            })
        }
        function unLogin() {
            alert("你还没有登录哦");
        }

        function ansyncSave(alp) {
            $.ajax({
                url: "/Album/Save",
                async: false,
                type: "post",
                data: { Alb_ID: alp },
                dataType: "json",
                success: function (list) {
                    var data = eval(list);
                    $("#save").val(data[0].sum);
                    $("#save").text(data[0].sum);
                    if (data[0].succ == 1) {
                        alert("你已经收藏过了哦");
                    } else {
                        alert("收藏成功");
                    }
                }
            })
        }
    </script>
</head>
<body>
    <section class="section-background">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index","Index")">主页</a></li>
                @if (Session["UID"] == null)
                {
                    <li class="active"><a href="@Url.Action("Index","Album")">&nbsp;相册</a></li>
                    <li class="active">&nbsp;相册详细</li>

                }
                else
                {
                    <li class="active"><a href="@Url.Action("Index","Album")">&nbsp;相册</a></li>
                    <li class="active">&nbsp;相册详细</li>
                    <li style="float:right;"><a href="@Url.Action("Album1","Album")">我的相册</a></li>
                }

                <li style="float:right">@Html.ActionLink("创建我的相册", "Add")  </li>
            </ol>


        </div>
    </section>
    <section class="about" id="about" style="background: #f3f3f3;">
        <div class="container section-wrapper">
            <h2 class="section-title black">
                相  册  详  细
            </h2>
            <div class="underline purple"></div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <img src="@Model.Album1.Alb_Pic" width="500" />
                </div>
                <div class="col-md-6 col-sm-12" style="height:350px">
                    <div style="font-size:20px;float:left;">
                        @Model.Album1.Alb_Name
                    </div>
                    <div style="float:right;">
                        <div style="margin-right:30px;">
                            <a href="@Url.Action("UserIndex","User",new {UID=Model.Album1.UserInfo.UID})">
                                @Model.Album1.UserInfo.User_Name
                            </a>
                        </div>
                        <div style="margin-left:40px;margin-top:-20px;">
                            <a href="@Url.Action("UserIndex","User",new {UID=Model.Album1.UserInfo.UID})"> <img src="@Model.Album1.UserInfo.User_Img" height="40" width="40" style=" display: flex;border-radius: 50%; align-items: center;justify-content: center;overflow: hidden;" /></a>
                        </div>
                    </div>
                    <br />
                    <hr />

                    <p class="about-detail">
                        &nbsp;
                    </p>
                    <p class="about-detail" style="font-size:15px;">
                        @Model.Album1.Alb_Mes
                        <br />
                    </p>
                    <div style="float:right;margin-bottom:10px;">
                        @Model.Album1.Alb_Time.ToString().Substring(0, 10)
                    </div>
                    <br />   <hr />
                    <div style="float:left;">
                        @if (Session["User_Name"] != null)
                        {
                            <button class="btn btn-success" onclick="asyncPoint(@Model.Album1.Alb_ID)">
                                <span >点赞 <span id="sum">@Model.Album_Point.Count()</span> </span>
                            </button> 
                        }
                        else
                        {
                            <button class="btn btn-success" onclick="unLogin()">
                                <span class="btn-outline-primary">点赞(@ViewBag.pc) </span>
                            </button>
                        }
                    </div>
                    <div style="float:right;">
                        @if (Session["User_Name"] != null)
                        {
                            <button class="btn btn-primary" onclick="ansyncSave(@Model.Album1.Alb_ID)">
                                <span>收藏<span id="save">@Model.Album_Save.Count()</span></span>
                            </button> 
                        }
                        else
                        {
                            <button class="btn btn-primary" onclick="unLogin()">
                                <span>收藏(@Model.Album_Save.Count()  )</span>
                            </button>
                        }
                    </div>                       
                </div>

            </div>
        </div>
    </section>

    <section class="team">
        <div class="container section-wrapper">
            <h2 class="section-title black">
                包  含  的  图  片
            </h2> <!-- /.section-title -->
            <div class="underline purple"></div>
            <div class="row">
                @{ Html.RenderAction("Index", "Picture_In_Album");}
            </div>
        </div>


    </section>

    <section class="team">
        <div class="row">
            <div class="container section-wrapper">
                @using (Html.BeginForm("AC_Add", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="col-md-12 col-xs-12 form-group">
                        <label class="sr-only">评论</label>
                        <textarea class="textarea form-control" style="height:100px" name="acmes" placeholder="写下评论"></textarea>
                    </div>
                    <input type="hidden" name="albid" value="@Model.Album1.Alb_ID" />
                    if (Session["UID"] != null)
                    {
                        <input type="submit" value="发表评论" class="btn btn-sub" style="float:right" />


                    }
                    else
                    {

                        <input type="submit" value="发表评论" class="btn btn-sub" style="float:right" />

                    }
                }
            </div>
        </div>


        <div class="row">
            <div class="container section-wrapper">
                <div class="col-md-12 col-xs-12 form-group">
                    <div>

                        @foreach (Album_Comment p in Model.Album_Comment)
                        {
                            <div style="float:left;margin-right:20px;">
                                <a href="@Url.Action("UserIndex","User",new {UID=p.UserInfo.UID})"> <img src="@p.UserInfo.User_Img" height="50" width="50" style=" display: flex;border-radius: 50%; align-items: center;justify-content: center;overflow: hidden;"  /></a>
                            </div>
                            <div style=" background: #f2fbf2;color: #666;padding: 2px 4px;">
                                <a href="@Url.Action("UserIndex","User",new {UID=p.UserInfo.UID})">@p.UserInfo.User_Name   </a>
                            </div>
                            <div style="float:right;margin-top:-20px;">
                                <span>    @p.AC_Time.ToString().Substring(0,10)</span>
                            </div>
                            <div style="margin-top:10px;margin-left:10px;">
                                <p> @p.AC_Mes</p>
                            </div>
                            <br />
                        }
                    </div>
                </div>
            </div>

        </div>


    </section>
</body>

SEEWeb/Views/Album/Index.cshtml
    @model List<Model.Album>
@{
    ViewBag.Title = "Index";

}

<section class="section-background">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Index")">主页</a></li>
            @if (Session["UID"] == null)
            {
                <li class="active">&nbsp;相册</li>
            }
            else
            {
                <li class="active">&nbsp;相册</li>
                <li style="float:right;"><a href="@Url.Action("Album1","Album")">我的相册</a></li>
            }


            <li style="float:right">@Html.ActionLink("创建我的相册", "Add")  </li>
        </ol> 
    </div>
</section>

    
            @{ Html.RenderAction("Album", "Album");}
 