SEEWeb/Controllers/ActPictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using BLL;

namespace SEEWeb.Controllers
{
    public class ActPictureController : Controller
    {
        ActPictureManager apm = new ActPictureManager();
        SEEEntities db = new SEEEntities();

        // GET: ActPicture
        public ActionResult Index(int id)
        {
            ActPicture ap = apm.GetById(id);
            return View(ap);
        }
        #region 设置第一名
        public ActionResult SetF(int acid,int apid)
        {
            var piaaa = (from u in db.PicInActivity
                         where u.Num==1
                         select u);
            int cou = piaaa.Count();
            if(cou == 0)
            {
                PicInActivity piaa = (from u in db.PicInActivity
                                      where u.Ac_ID == acid && u.AP_ID == apid
                                      select u).FirstOrDefault();
                if (piaa != null)
                {
                    PicInActivity pia = db.PicInActivity.Find(piaa.PIAC_ID);
                    pia.Num = 1;
                    db.SaveChanges();
                    return Content("<script>;alert('添加成功');history.go(-1)</script>");
                }
            }
            else
            {
                return Content("<script>;alert('已经有第一了哦');history.go(-1)</script>");
            }
           
            return View();
        }
        #endregion

        #region 设置第二名
        public ActionResult SetS(int acid, int apid)
        {
            var piaaa = (from u in db.PicInActivity
                         where u.Num == 2
                         select u);
            int cou = piaaa.Count();
            if (cou == 0)
            {
                PicInActivity piaa = (from u in db.PicInActivity
                                      where u.Ac_ID == acid && u.AP_ID == apid
                                      select u).FirstOrDefault();
                if (piaa != null)
                {
                    PicInActivity pia = db.PicInActivity.Find(piaa.PIAC_ID);
                    pia.Num = 2;
                    db.SaveChanges();
                    return Content("<script>;alert('添加成功');history.go(-1)</script>");
                }
            }
            else
            {
                return Content("<script>;alert('已经有第二了哦');history.go(-1)</script>");
            }

            return View();
        }
        #endregion

        #region 设置第三名
        public ActionResult SetT(int acid, int apid)
        {
            var piaaa = (from u in db.PicInActivity
                         where u.Num == 3
                         select u);
            int cou = piaaa.Count();
            if (cou == 0)
            {
                PicInActivity piaa = (from u in db.PicInActivity
                                      where u.Ac_ID == acid && u.AP_ID == apid
                                      select u).FirstOrDefault();
                if (piaa != null)
                {
                    PicInActivity pia = db.PicInActivity.Find(piaa.PIAC_ID);
                    pia.Num = 3;
                    db.SaveChanges();
                    return Content("<script>;alert('添加成功');history.go(-1)</script>");
                }
            }
            else
            {
                return Content("<script>;alert('已经有第三了哦');history.go(-1)</script>");
            }

            return View();
        }
        #endregion

        #region 取消名次
        public ActionResult SetNon(int acid,int apid)
        {
            PicInActivity piaa = (from u in db.PicInActivity
                                  where u.Ac_ID == acid && u.AP_ID == apid
                                  select u).FirstOrDefault();
            PicInActivity pia = db.PicInActivity.Find(piaa.PIAC_ID);
            pia.Num = 0;
            db.SaveChanges();
            return Content("<script>;alert('取消成功');history.go(-1)</script>");
        }
        #endregion
    }
}

SEEWeb/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using PagedList;
using Model;

namespace SEEWeb.Controllers
{
    public class ActivityController : Controller
    {
        ActivityManager am = new ActivityManager();
        ActPictureManager actpicm = new ActPictureManager();
        SEEEntities db = new SEEEntities();
        #region 相册主页
        // GET: Activity
        public ActionResult Index(int ? page)
        {
            var act = (from p in db.Activity select p).ToList().OrderBy(p => p.Ac_Sta_Time).ToList();//显示点赞最多的八个相册
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(act.ToPagedList(pageNumber,pageSize));
        }
        #endregion

        #region 活动发起
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Activity activity)
        {
            HttpPostedFileBase file = Request.Files["actimage"];
            
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string filePath = file.FileName;
                    string fileName = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                    string serverpath = Server.MapPath(@"\images\activitys\") + fileName;
                    string relativepath = @"/images/activitys/" + fileName;
                    file.SaveAs(serverpath);
                    activity.Ac_Pic = relativepath;
                }
                activity.Ac_Name = Request["ActivityName"];
                activity.Ac_Mes = Request["ActivityMes"];
                DateTime startdate = Convert.ToDateTime(Request["startdate"]);
                DateTime endtime = Convert.ToDateTime(Request["stopdate"]);
                activity.Ac_Sto_Time = endtime;
                activity.Ac_Sta_Time = startdate;
                activity.IsAct = 1;
                am.Add(activity);
                return Content("<script>alert('添加成功！');window.open('" + Url.Action("List", "Activity") + "','_self');</script>");
            }
            return View(activity);
        }
        #endregion

        #region 活动查询
        public ActionResult List(int ? page,string search)
        {
            Session["User_Name"] = null;
            var list = new List<Activity>();
            if(search != null)
            {
                var acts = (from p in db.Activity select p).Where(a => (a.Ac_Mes.Contains(search)) || (a.Ac_Name.Contains(search))).ToList();
                list = acts;
            }
            else
            {
                var acts = am.List();
                list = acts;
            }        
            int pageSize = 9;
            int pageNumber=(page ?? 1);
            return View(list.ToPagedList(pageNumber,pageSize));
        }
        #endregion

        #region 活动删除
        public ActionResult Delete(int id)
        {
            var activity = am.Remove(id);
            if(activity==true)
                return Content("<script>alert('删除成功！');window.open('" + Url.Action("List", "Activity") + "','_self');</script>");
            else
                return View();
        }
        #endregion

        #region 活动详细
        public ActionResult Details(int id)
        {
            Activity activity1 = db.Activity.Find(id);
            var picinact = from p in db.PicInActivity.Where(p => p.Ac_ID == id)
                           select p;
            var activity2 = from p in db.Activity.OrderBy(p => p.Ac_Sta_Time)
                            select p;
            PicInActivity first = (from p in db.PicInActivity.Where(p => p.Num == 1).Where(a => a.Ac_ID==id) select p).FirstOrDefault();
            PicInActivity second = (from p in db.PicInActivity.Where(p => p.Num == 2).Where(a => a.Ac_ID == id) select p).FirstOrDefault();
            PicInActivity third = (from p in db.PicInActivity.Where(p => p.Num == 3).Where(a => a.Ac_ID == id) select p).FirstOrDefault();
            ViewBag.first = first;
            ViewBag.second = second;
            ViewBag.third = third;
            var index = new SEEWeb.ViewModel.ActivityDetailViewModel()
            {
                Activity1 = activity1,
                PicInActivity = picinact,
                Activity2 = activity2,
                First = first,
                Second=second,
                Third=third,
            };
            return View(index);
        }
        #endregion

        #region 参与活动
        public ActionResult Attend()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Attend(ActPicture actpic,PicInActivity picinact)
        {
            int id=Convert.ToInt32(Request["Ac_ID"]);
            Activity act = (from p in db.Activity where p.Ac_ID == id select p).FirstOrDefault();
            if (act.IsAct != 0)
            {
             if (Session["UID"] != null)
             {
                HttpPostedFileBase file = Request.Files["img"];
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {
                        string filePath = file.FileName;
                        string fileName = filePath.Substring(filePath.LastIndexOf("\\") + 1);
                        string serverpath = Server.MapPath(@"\images\actpic\") + fileName;
                        string relativepath = @"/images/actpic/" + fileName;
                        file.SaveAs(serverpath);
                        actpic.AP_Pic = relativepath;
                        actpic.UID = Convert.ToInt32(Session["UID"].ToString());
                        actpic.AP_Mes = Request["Mes"];
                        actpic.AP_Time = DateTime.Now;
                        actpicm.Add(actpic);
                        string ap_id = actpic.AP_ID.ToString();
                        picinact.Ac_ID = Convert.ToInt32(Request["Ac_ID"]);
                        picinact.AP_ID = Convert.ToInt32(ap_id);
                        db.PicInActivity.Add(picinact);
                        db.SaveChanges();
                        return Content("<script>;alert('添加成功');history.go(-1)</script>");
                    }
                    return View();
                }
            }
            else
            {
                return Content("<script>;alert('你还没有登陆哦!');history.go(-1)</script>");
            }
          }
            else
            {
                return Content("<script>;alert('活动已经结束了哦!');history.go(-1)</script>");
            }
            return View();
        }
        #endregion

        #region 我的参与
        public ActionResult MyAtt(int ? page)
        {
            int UID = Convert.ToInt32(Session["UID"].ToString());
            var Activity = (from a in db.Activity
                            join b in db.PicInActivity on a.Ac_ID equals b.Ac_ID
                            join c in db.ActPicture.Where(c => c.UID==UID) on b.AP_ID equals c.AP_ID select a).Distinct().ToList();
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(Activity.ToPagedList(pageNumber,pageSize));
        }
        #endregion

        #region 活动结束
        public ActionResult End(int id)
        {
            Activity act = (from p in db.Activity where p.Ac_ID==id select p).FirstOrDefault();
            act.IsAct = 0;
            db.SaveChanges();
            return Content("<script>;alert('活动取消成功');history.go(-1)</script>");
        }
        #endregion

        #region 控制信息长度
        [HttpGet]
        public string strLength(string news)
        {
            int length = news.Length;
            string dotDot = "...";
            if (length >= 50)
            {
                string cutStr = news.Substring(0, 50);
                string endNews = String.Format("{0}{1}", cutStr, dotDot);
                return endNews;
            }
            else
            {
                return news;
            }
        }
        #endregion
    }
}

SEEWeb/Views/Activity/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}
<!DOCTYPE>
<html>
<head>
</head>
<body>
    <div class="layui-row">
        <blockquote class="layui-elem-quote layui-text">
            活动添加
        </blockquote>
    </div>

    @using (Html.BeginForm("Add", "Activity", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="layui-form">
            <div class="layui-form-item">
                <div class="layui-form-item">
                    <label class="layui-form-label">活动标题</label>
                    <div class="layui-input-block">
                        <input type="text" id="ActivityName" name="ActivityName" lay-verify="required" placeholder="请输入活动标题" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">开始时间</label>
                    <div class="layui-input-inline">
                        <input type="text" class="layui-input" id="startdate" name="startdate" placeholder="yyyy-MM-dd">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label">结束时间</label>
                    <div class="layui-input-inline">
                        <input type="text" class="layui-input" id="stopdate" name="stopdate" placeholder="yyyy-MM-dd">
                    </div>
                </div>
            </div>
            <div class="layui-form-item layui-form-text">
                <label class="layui-form-label">活动描述</label>
                <div class="layui-input-block">
                    <textarea placeholder="请输入内容" id="ActivityMes" name="ActivityMes" lay-verify="required" class="layui-textarea"></textarea>
                </div>
            </div>
            <div class="layui-form-item" style="margin-left:50px;">
                <div class="layui-input-inline">
                    <input type="file" name="actimage" id="actimage" />
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" type="submit" lay-submit="">立即提交</button>
                </div>
            </div>
        </div>
    }
    </body>

</html>

SEEWeb/Views/Activity/Details.cshtml
@using PagedList.Mvc;
@using Model;
@model SEEWeb.ViewModel.ActivityDetailViewModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<head>
    <script src="~/Content/layui/layui.js"></script>
    <script src="~/Content/foundation/jquery-1.11.1.min.js"></script>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" /> 
</head>
<div>
    <section class="section-background">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index","Index")">主页</a></li>
                @if (Session["UID"] == null)
                {
                    <li class="active"><a href="@Url.Action("Index","Activity")">&nbsp;活动</a></li>
                    <li class="active">&nbsp;活动详细</li>

                }
                else
                {
                    <li class="active"><a href="@Url.Action("Index","Activity")">&nbsp;活动</a></li>
                    <li class="active">&nbsp;活动详细</li>
                    <li style="float:right;"><a href="@Url.Action("MyAtt","Activity")">我的参与</a></li>
                }
                @if (Session["Man_ID"] != null)
                {
                    <li style="float:right;"><a href="@Url.Action("List","Activity")">活动列表</a></li>
                }

            </ol>


        </div>
    </section>
    <section class="about" id="about" style="background: #f3f3f3;">
        <div class="container section-wrapper">
            <h2 class="section-title black">
                活动详细
            </h2>
            <div class="underline purple"></div>
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <img src="@Model.Activity1.Ac_Pic" width="500" />
                </div>
                <div class="col-md-6 col-sm-12" style="height:350px">
                    <p class="about-detail" style="font-size:25px; ">
                        @Model.Activity1.Ac_Name
                        <hr />
                    </p>
                    <p class="about-detail">
                        &nbsp;
                    </p>
                    <p class="about-detail">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Activity1.Ac_Mes
                        <br />
                    </p>
                    <p class="about-detail">
                        &nbsp;
                    </p>
                    <hr />
                    <p class="about-detail">
                        <div style="float:left">
                            开始时间:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Activity1.Ac_Sta_Time.ToString("yyyy-MM-dd")
                        </div>
                        <div style="float:right">
                            结束时间:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Activity1.Ac_Sto_Time.ToString("yyyy-MM-dd")
                        </div>
                    </p>
                    <br />
                    <hr />
                    <p class="about-detail">

                        <br />
                        <br />
                    </p>
                    @if (Session["Man_ID"] != null)
                    {
                        <p class="about-detail">
                            <a class="center-align layui-btn layui-btn-sm layui-btn-danger" href="@Url.Action("End","Activity",new {id=Model.Activity1.Ac_ID})">
                                活动结束
                            </a>
                            <br /><br />
                        </p>
                    }

                    <div class="up" style="display:none">
                        @using (Html.BeginForm("Attend", "Activity", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {

                            <br />
                            <form class="layui-form">
                                <div style="float:left;margin-left:110px;">
                                    <input type="file" name="img" id="img" />
                                    <br /><br />
                                    <input type="hidden" id="Ac_ID" name="Ac_ID" value="@Model.Activity1.Ac_ID" />
                                </div>
                                <div class="layui-form-item layui-form-text">
                                    <div class="layui-input-block">
                                        <textarea class="layui-textarea" placeholder="请输入图片描述" id="Mes" name="Mes"></textarea>
                                    </div>
                                </div>
                                <div style="float:right;">
                                    <button id="shangchuan" class="layui-btn layui-btn-normal" type="submit">上传图片</button>
                                </div>
                            </form>

                        }
                    </div>
                    @if (Session["Man_ID"] == null)
                    {
                        <button class="layui-btn layui-btn-normal" id="btn-show">立即参与</button>
                        <button style="display:none;margin-left:110px;" class="layui-btn layui-btn-danger" id="btn-hide">不参加了</button>
                    }
                </div>
            </div>
        </div>
    </section>
    <section class="team" style="background: #f3f3f3;margin-top:1px;">
        <div class="container section-wrapper">
            <h2 class="section-title black">
                获奖名单
            </h2> 
            <div class="underline purple"></div>
            <div class="row">

                @if (ViewBag.second != null)
                {
                    <div class="col-md-4">
                        <div class="section-title" style="font-size:20px;color:deepskyblue">
                            第二名
                        </div> 
                       <div class="underline purple"></div>
                        <div class="team-item" >
                            <div style="height:250px;overflow:hidden;">
                                <a href="@Url.Action("Index","ActPicture",new {id=Model.Second.ActPicture.AP_ID})">
                                    <img src="@Model.Second.ActPicture.AP_Pic" alt="team-image" class="team-img" style="width:380px">
                                </a>
                            </div>
                           
                            <br /> 
                            @if (Session["Man_ID"] != null)
                            {
                                <a class="center-align layui-btn layui-btn-sm layui-btn-danger" href="@Url.Action("SetNon","ActPicture",new { acid=Model.Second.Activity.Ac_ID,apid=Model.Second.ActPicture.AP_ID})">取消</a>
                            }
                        </div>
                    </div>
                }
                &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
                @if (ViewBag.first != null)
                {
                    <div class="col-md-4">
                        <div class="section-title" style="font-size:20px;color:deepskyblue;">
                            第一名
                        </div>
                        <div class="underline purple"></div>
                        <div class="team-item">
                            <div style="height:250px;overflow:hidden;">
                                <a href="@Url.Action("Index","ActPicture",new {id=Model.First.ActPicture.AP_ID})">
                                    <img src="@Model.First.ActPicture.AP_Pic" alt="team-image" class="team-img" style="width:380px">
                                </a>
                            </div>
                            <br />
                            @if (Session["Man_ID"] != null)
                            {
                                <a class="center-align layui-btn layui-btn-sm layui-btn-danger" href="@Url.Action("SetNon","ActPicture",new { acid=Model.First.Activity.Ac_ID,apid=Model.First.ActPicture.AP_ID})">取消</a>
                            }
                        </div>
                    </div>
                }

                @if (ViewBag.third != null)
                {
                    <div class="col-md-4" style="margin-top:-17px;">
                        <div class="section-title" style="font-size:20px;color:deepskyblue">
                            第三名
                        </div>
                        <div class="underline purple"></div>
                        <div class="team-item">
                            <div style="height:250px;overflow:hidden;">
                                <a href="@Url.Action("Index","ActPicture",new {id=Model.Third.ActPicture.AP_ID})">
                                    <img src="@Model.Third.ActPicture.AP_Pic" alt="team-image" class="team-img" style="width:380px">
                                </a>
                            </div>
                            <br />
                            @if (Session["Man_ID"] != null)
                            {
                                <a class="center-align layui-btn layui-btn-sm layui-btn-danger" href="@Url.Action("SetNon","ActPicture",new { acid=Model.Third.Activity.Ac_ID,apid=Model.Third.ActPicture.AP_ID})">取消</a>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
            <section class="team">
                <div class="container section-wrapper">
                    <h2 class="section-title black">
                         活动图片
                    </h2>  
                    <div class="underline purple"></div>
                    <div class="row">
                        @foreach (var p in Model.PicInActivity)
                        {
                            <div class="col-sm-3 col-xs-6" style="margin-top:20px;">
                                <div class="team-item">
                                    <div style="height:195px;overflow:hidden;">
                                        <a href="@Url.Action("Index","ActPicture",new {id=p.ActPicture.AP_ID})">
                                            <img src="@p.ActPicture.AP_Pic" alt="team-image" class="team-img" style="width:270px;">
                                        </a>
                                    </div>                                                                  
                                    <p class="team-item-id" style="float:right;margin-top:5px;">
                                        <a href="@Url.Action("UserIndex","User",new {UID=p.ActPicture.UserInfo.UID})">
                                            @p.ActPicture.UserInfo.User_Name
                                        </a>
                                    </p>
                                    @if (Session["Man_ID"] != null)
                                    {
                                    <div style="float:right">
                                        <a class="layui-btn layui-btn-sm layui-btn-normal" href="@Url.Action("SetF","ActPicture",new { acid=p.Activity.Ac_ID,apid=p.ActPicture.AP_ID})">第一</a>
                                        <a class="layui-btn layui-btn-sm layui-btn-normal" href="@Url.Action("SetS","ActPicture",new { acid=p.Activity.Ac_ID,apid=p.ActPicture.AP_ID})">第二</a>
                                        <a class="layui-btn layui-btn-sm layui-btn-normal" href="@Url.Action("SetT","ActPicture",new { acid=p.Activity.Ac_ID,apid=p.ActPicture.AP_ID})">第三</a>

                                    </div>
                                        }
                                </div> <!-- /.team-item -->
                            </div>
                        }
                    </div>
                </div>
            </section>
        </div>
<script>
    layui.use('form', function () {
        var form = layui.form;
        form.render();
    });
</script>
        <script>
            $(document).ready(function () {
                $("#btn-show").click(function () {
                    $(".up").show();
                    $("#btn-show").hide();
                    $("#btn-hide").show();
                });
                $("#btn-hide").click(function () {
                    $(".up").hide();
                    $("#btn-show").show();
                    $("#btn-hide").hide();
                })
            });
        </script>

SEEWeb/Views/Activity/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Model.Activity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section-background">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","Index")">主页</a></li>
            @if (Session["UID"] == null)
            {
            <li class="active">&nbsp;<a href="@Url.Action("Index","Activity")">活动</a></li>
            }
            else
            {
            <li class="active">&nbsp;<a href="@Url.Action("Index","Activity")">活动</a></li>
                <li style="float:right;"><a href="@Url.Action("MyAtt","Activity")">我的参与</a></li>
            }
        </ol>
    </div>
</section>
<section class="portfolio" id="portfolio">
    <div class="container section-wrapper">
        <h2 class="section-title black">
            活  动
        </h2>
        <div class="underline purple"></div>
        <div class="row">
            @foreach (var p in Model)
            {
                <div class="col-sm-4 col-xs-6">
                    <div class="portfolio-item">
                        <div class="portfolio-img">
                            <img src="@p.Ac_Pic" alt="port3" height="280" />

                            <div class="portfolio-img-hover">
                                <a href="@Url.Action("Details",new {id=p.Ac_ID})"><img src="~/Content/_share/User/assets/images/plus.png" class="plus"></a>
                            </div>
                        </div>
                        <div class="portfolio-item-details">
                            <div style="text-align:center" class="portfolio-item-name">
                                <a style="text-align:center" href="@Url.Action("Details",new { id=p.Ac_ID})">@p.Ac_Name</a>
                            </div>
                            <div class="port-heart">
                                <i class="ion-ios-heart-outline"></i>  @p.PicInActivity.Count()
                            </div>
                        </div>

                    </div>
                </div>
            }
        </div>
    </div>
    <div class="container">
        <div style="float:right">
            <div>
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </div>
            <div>
                @Html.PagedListPager(Model, page => Url.Action("Index", "Activity", new { page }))
            </div>
        </div>

    </div>
</section>